ingress:
  main:
    enabled: true
    hosts:
      - host: auth.example.com
        paths:
          - path: /
            pathType: Prefix
authelia:
  authentication_backend:
    file:
      path: /config/users.yaml
  notifier:
    filesystem:
      filename: /config/notification.txt
