workload:
  main:
    enabled: true
    podSpec:
      containers:
        main:
          enabled: true
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8080
        protocol: http
  autolink:
    enabled: true
    ports:
      autolink:
        enabled: true
        protocol: http
        port: 8081

# -- Configure the ingresses for the chart here.
# Additional ingresses can be added by adding a dictionary key similar to the 'main' ingress.
# @default -- See below
ingress:
  main:
    enabled: true
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

  certificateissuer:
    enabled: true
    certificateIssuer: someissuer
    hosts:
      - host: ci.chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name:
              port:
    tls:
      - hosts:
          - ci.chart-example.local

  tlscertificateissuer:
    enabled: true
    hosts:
      - host: citls.chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name:
              port:
    tls:
      - certificateIssuer: sometlsissuer
        hosts:
          - citls.chart-example.local

  label:
    enabled: true
    labels:
      labelexample1: labelvalue2
    hosts:
      - host: label.chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name:
              port:
    tls: []

  autolink:
    enabled: true
    hosts:
      - host: label.chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name:
              port:
    tls: []
    autoLink: true

  notls:
    enabled: true
    hosts:
      - host: notls.chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name:
              port:
